### ISSUE TITLE
HDDS duplicate columns

### ISSUE THREAD

**Issue by l-gorman** [l-gorman/rhomis-R-package#16]
HDDS 14 group and HDDS 10 group have overlaps in column names. This could be problematic when merging the datasets all together.

**Comment by rfrelat** [comment]
Indeed there is an error in the function collapse_14_groups() for nuts_seeds (because the category is both in 14 groups and 10 groups). 
As you did for 'eggs', you should comment or remove the lines:
  hdds_data$nuts_seeds <- hdds_data$nuts_seeds
  hdds_data$nuts_seeds <- NULL

Else the nuts and seeds is considered as 0 for all households, even those who consume it frequently (hence causing an underestimation of HDDS).  For instance, id_hh:
190e8480d436a75380df89367f4b7f01
391d7de95b4a831d3c154dbc89fe3841
29a1450251f8d3c14d4479d62cc814e9
66ed671e1ade5f6a693e8d00c051b8ea
8dc62236faa2581c090717e89d7a804d

**Comment by l-gorman** [comment]
Thanks @rfrelat, well spotted again. I will work on this in the PR for [this branch](https://github.com/l-gorman/rhomis-R-package/tree/analysis-stages)
